name: mrs

on:
  workflow_dispatch:
  schedule:
    # 表达式生成 https://crontab.guru/
    - cron: "0 0 * * *" #北京时间上午8点
  push:
    paths:
      - ".github/workflows/mrs.yml"
      - "mrs/start.sh"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 运行脚本
        run: |
          sh ./mrs/start.sh

      - name: 推送更改
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          branch: main
          force: true
